# DTEP-F Taler Integration Notes

**Version:** 0.1-draft
**Date:** 2026-06-01
**Audience:** GNU Taler development team, Taler Exchange implementers
**Authors:** CSDT / SolidarityLab

---

## Overview

This document describes DTEP-F's integration with GNU Taler in technical detail, written directly for the Taler ecosystem. It covers the DD-18 extension, the M0 coin commitment binding, the auditor protocol integration, and the expected contributions to Taler core.

DTEP-F is the first implementation of GNU Taler DD-18 in a tax reporting context. The integration reuses existing Taler components and extends them in two specific ways described below.

---

## 1. DD-18 Extension — Salt Derivation from M0

### Standard DD-18 behaviour

In the standard DD-18 forgettable fields mechanism, the salt for each forgettable field is an independent random value generated at scrubbing time. The salt is stored by the Exchange and disclosed selectively.

### DTEP-F extension

DTEP-F derives the DD-18 salt from the M0 coin commitment via HKDF-SHA512 (RFC 5869):

```
salt = HKDF-SHA512(
  ikm  = m0_coin_commitment,
  info = "dtep-f-dd18-salt-v1",
  length = 64
)
```

**Rationale:** This binds the scrubbing cryptographically to the invoice identifier. A party that can verify M0 can also verify that the scrubbing was performed correctly — without access to the original values. The salt is no longer an independent secret; it is a deterministic derivative of M0.

**Impact on Taler core:** The salt derivation function must be configurable per Exchange deployment. Standard DD-18 (random salt) and DTEP-F DD-18 (HKDF salt from coin commitment) should coexist as configuration options.

**Known limitation:** HKDF derivation makes the salt predictable given M0. An observer with M0 and the original field value can verify the scrubbing independently. This is intentional for DTEP-F — it enables third-party scrubbing verification — but may not be appropriate for all DD-18 use cases.

---

## 2. M0 Coin Commitment as Invoice Reference

### Standard Taler coin lifecycle

In standard Taler, a coin is withdrawn by a wallet, spent at a merchant, and deposited at the Exchange. The coin commitment is internal to the wallet-Exchange protocol.

### DTEP-F extension

DTEP-F uses the coin commitment as an external invoice reference — a stable, unlinkable identifier for a B2B invoice in the DRRDB public layer. The coin is not withdrawn by a wallet in the traditional sense; it is generated by the Exchange directly upon receipt of an EN 16931 invoice from Corner 5 Middleware.

**New flow:**

```
Corner 5 Middleware → Exchange: submit EN 16931 invoice
Exchange → Corner 5 Middleware: coin commitment (M0) + signed public DTEP JSON
Exchange → internal: store Artifact A (encrypted audit record)
Exchange → Merchant (seller): Taler Contract Terms with M0 as order_id
```

**Required Exchange API extension:** A new endpoint (or extension of an existing endpoint) to generate a coin commitment directly from an invoice identifier, without wallet withdrawal. This is a new flow not present in the current Exchange API.

**Proposed endpoint:** `POST /exchange/v1/dtep/commit`

Input: invoice identifier + EN 16931 metadata
Output: coin commitment + HKDF-derived salt + signed public DTEP JSON

This endpoint is the primary contribution DTEP-F makes to Taler Exchange API.

---

## 3. Auditor Protocol Integration

### Standard Taler auditor

The Taler auditor verifies the financial balance between Exchange and merchants: every coin deposited at Exchange has a corresponding withdrawal. The invariant is: sum(withdrawals) = sum(deposits) + sum(fees).

### DTEP-F integration

DTEP-F uses the Taler auditor to verify a different invariant: every public DTEP JSON object in DRRDB has a corresponding Artifact A in Exchange custody.

**Invariant:** ∀ m0 ∈ DRRDB_public: ∃ artifact_a ∈ Exchange_custody with artifact_a.m0_reference = m0

**Required auditor extension:** The auditor protocol must support a new check type — "evidence completeness" — distinct from the financial balance check. This requires:
- A new auditor query to Exchange: list all M0 coin commitments generated via the DTEP endpoint
- A corresponding query to DRRDB: list all M0 values in the public level
- Set difference detection: M0 in Exchange but not in DRRDB, or vice versa

This is an additive extension — it does not modify the existing financial balance check.

---

## 4. Taler Contract Terms for B2B Invoice Payment

### Standard Contract Terms

Taler Contract Terms are generated by the merchant backend for each payment. The wallet reads them, presents them to the user, and executes payment on confirmation.

### DTEP-F usage

DTEP-F generates Contract Terms with M0 as the `order_id`. This creates an explicit binding between the DRR evidence record and the payment. See [spec/payment-interface.md](../spec/payment-interface.md) for the full Contract Terms schema.

**No changes to Contract Terms format required.** The existing `order_id` field accommodates M0. The `products` array uses CPV codes as descriptions — this is a semantic convention, not a format change.

**Recommended addition:** A standardised extension field `dtep_m0_reference` in Contract Terms to make the DRR binding machine-readable for Taler tooling:

```json
{
  "order_id": "dtep-m0-<coin_commitment>",
  "dtep_m0_reference": {
    "commitment": "<coin_commitment>",
    "public_record_id": "urn:uuid:<uuid>",
    "exchange": "https://exchange.example.eu/"
  }
}
```

---

## 5. Known Limitations of DD-18 in EN 16931 Context

### Free-text fields

EN 16931 allows free-text fields (BT-22 Note, BT-13 Purchase order reference, line item descriptions) that may contain subject-identifying information. The current DD-18 forgettable fields mapping covers structured fields (VAT number, IBAN, entity name, address) but does not cover free-text fields.

**Open issue:** A scrubbing policy for free-text fields requires either:
- Full scrubbing (treat entire free-text as forgettable) — loses analytical value
- NLP-based entity detection before scrubbing — complex, language-dependent
- Prohibition of subject-identifying information in free-text fields in DTEP-F profiles

This is documented in [docs/gdpr-analysis.md](gdpr-analysis.md) Section 8 as an open issue for v0.2.

### Multi-currency invoices

DTEP-F v0.1 fixes M5 to EUR. EN 16931 supports any ISO 4217 currency. Multi-currency support requires exchange rate handling in M5 and R(c,t) — deferred to v0.3.

### Partial invoice matching

When a buyer partially pays an invoice, the remaining balance must be tracked. Taler's refund protocol handles this at the payment layer, but the DRRDB protected level must reflect partial settlement correctly. The lifecycle mapping is an open issue for v0.2 (see [spec/payment-interface.md](../spec/payment-interface.md) Section 8).

---

## 6. Expected Contributions to Taler Core

| Contribution | Component | Priority |
|---|---|---|
| DTEP commit endpoint | Exchange API | High — required for reference implementation |
| HKDF salt derivation option | DD-18 implementation | High — required for scrubbing binding |
| Evidence completeness auditor check | Auditor protocol | Medium — required for Level 2 conformance |
| dtep_m0_reference Contract Terms extension | Merchant backend | Low — recommended for tooling |
| B2B invoice UX profile | Wallet | Low — post-implementation |

CSDT will coordinate with the Taler development team through the GNU Taler Integration Community Hub and will submit pull requests for the high-priority contributions during Period 2 of the project (months 4–6).

---

## References

- GNU Taler DD-18: https://docs.taler.net/design-documents/018-forgettable-json.html
- GNU Taler Exchange HTTP API: https://docs.taler.net/taler-exchange-httpapi.html
- GNU Taler Auditor Manual: https://docs.taler.net/taler-auditor-manual.html
- RFC 5869 HKDF: https://www.rfc-editor.org/rfc/rfc5869
- DTEP-F transformation layer: [spec/transformation-layer.md](../spec/transformation-layer.md)
- DTEP-F signing layer: [spec/signing-layer.md](../spec/signing-layer.md)
- DTEP-F DRRDB layer: [spec/drrdb-layer.md](../spec/drrdb-layer.md)
- DTEP-F payment interface: [spec/payment-interface.md](../spec/payment-interface.md)
